apiVersion: v1
kind: Service
metadata:
  name: misskey-web-service
spec:
  type: {{ .Values.misskey.web.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.misskey.web.service.port | default 3000 }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: misskey